name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.BOT_TOKEN }}
          release-type: node
          package-name: 'ml-array-utils'
          bump-minor-pre-major: true
      - uses: actions/checkout@v4
        # These if statements ensure that a publication only occurs when a new release is created
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - name: Run Lerna publish
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config --global user.name "mljs-bot"
          git config --global user.email "72700744+mljs-bot@users.noreply.github.com"
          npm install
          npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOT_TOKEN }}
